package at.htlle.freq.domain;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Repository abstraction for working with {@link Account} customer accounts
 * stored in the {@code Account} table.
 */
public interface AccountRepository {
    /**
     * Retrieves a customer account by its primary key.
     *
     * @param id identifier generated by the database
     * @return the customer account if it exists
     */
    Optional<Account> findById(UUID id);

    /**
     * Finds a customer account by its business name.
     *
     * @param name unique business name
     * @return optional containing the customer account when present
     */
    Optional<Account> findByName(String name);

    /**
     * Persists the supplied customer account instance.
     *
     * @param account aggregate to create or update
     * @return the managed entity after persistence
     */
    Account save(Account account);

    /**
     * Lists all customer accounts stored in the repository.
     *
     * @return every known customer account entity
     */
    List<Account> findAll();

    /**
     * Removes a customer account with the provided identifier.
     *
     * @param id primary key of the customer account to delete
     */
    void deleteById(UUID id);
}
