// at/htlle/freq/domain/AccountRepository.java (oder dein Repo-Package)
package at.htlle.freq.domain;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

/**
 * Repository abstraction for working with {@link Account} aggregates.
 */
public interface AccountRepository {
    /**
     * Retrieves an account by its primary key.
     *
     * @param id identifier generated by the database
     * @return the account if it exists
     */
    Optional<Account> findById(UUID id);

    /**
     * Finds an account by its business name.
     *
     * @param name unique business name
     * @return optional containing the account when present
     */
    Optional<Account> findByName(String name);

    /**
     * Persists the supplied account instance.
     *
     * @param account aggregate to create or update
     * @return the managed entity after persistence
     */
    Account save(Account account);

    /**
     * Lists all accounts stored in the repository.
     *
     * @return every known account entity
     */
    List<Account> findAll();

    /**
     * Removes an account with the provided identifier.
     *
     * @param id primary key of the account to delete
     */
    void deleteById(UUID id);
}
