package at.htlle.freq.domain;

import org.springframework.stereotype.Component;
import java.util.UUID;

@Component
public class ServiceContractFactory {
    /**
     * Creates a {@link ServiceContract} tying together customer account,
     * project, and optionally site-level responsibilities. The contract id is
     * generated by the persistence tier.
     *
     * @param accountID owning customer {@link Account} identifier
     * @param projectID related {@link Project} identifier
     * @param siteID optional {@link Site} identifier
     * @param contractNumber external contract number
     * @param status workflow status of the contract
     * @param startDate contract start date as string
     * @param endDate contract end date as string
     * @return transient service contract entity
     */
    public ServiceContract create(UUID accountID, UUID projectID, UUID siteID,
                                  String contractNumber, String status,
                                  String startDate, String endDate) {
        return new ServiceContract(null, accountID, projectID, siteID, contractNumber, status, startDate, endDate);
    }
}
