package at.htlle.freq.infrastructure.persistence;

import at.htlle.freq.domain.AudioDevice;
import at.htlle.freq.domain.AudioDeviceRepository;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.*;
import org.springframework.stereotype.Repository;

import java.util.*;

/**
 * Repository for {@link AudioDevice} entities that encapsulates direct JDBC access to the
 * {@code AudioDevice} table and maps all relevant columns to domain objects.
 */
@Repository
public class JdbcAudioDeviceRepository implements AudioDeviceRepository {

    private final NamedParameterJdbcTemplate jdbc;

    /**
     * Creates a new JdbcAudioDeviceRepository instance and initializes it with the provided values.
     * @param jdbc jdbc.
     */
    public JdbcAudioDeviceRepository(NamedParameterJdbcTemplate jdbc) { this.jdbc = jdbc; }

    private final RowMapper<AudioDevice> mapper = (rs, n) -> new AudioDevice(
            rs.getObject("AudioDeviceID", UUID.class),
            rs.getObject("ClientID", UUID.class),
            rs.getString("AudioDeviceBrand"),
            rs.getString("DeviceSerialNr"),
            rs.getString("AudioDeviceFirmware"),
            rs.getString("DeviceType"),
            rs.getString("Direction")
    );

    /**
     * Finds By ID using the supplied criteria and returns the matching data.
     * @param id identifier.
     * @return the matching By ID.
     */
    @Override
    public Optional<AudioDevice> findById(UUID id) {
        String sql = """
            SELECT AudioDeviceID, ClientID, AudioDeviceBrand, DeviceSerialNr, AudioDeviceFirmware, DeviceType, Direction
            FROM AudioDevice WHERE AudioDeviceID = :id
            """;
        try { return Optional.ofNullable(jdbc.queryForObject(sql, new MapSqlParameterSource("id", id), mapper)); }
        catch (org.springframework.dao.EmptyResultDataAccessException e) { return Optional.empty(); }
    }

    /**
     * Finds By Client using the supplied criteria and returns the matching data.
     * @param clientId client identifier.
     * @return the matching By Client.
     */
    @Override
    public List<AudioDevice> findByClient(UUID clientId) {
        String sql = """
            SELECT AudioDeviceID, ClientID, AudioDeviceBrand, DeviceSerialNr, AudioDeviceFirmware, DeviceType, Direction
            FROM AudioDevice WHERE ClientID = :cid
            """;
        return jdbc.query(sql, new MapSqlParameterSource("cid", clientId), mapper);
    }

    /**
     * Finds All using the supplied criteria and returns the matching data.
     * @return the matching All.
     */
    @Override
    public List<AudioDevice> findAll() {
        return jdbc.query("""
            SELECT AudioDeviceID, ClientID, AudioDeviceBrand, DeviceSerialNr, AudioDeviceFirmware, DeviceType, Direction
            FROM AudioDevice
            """, mapper);
    }

    /**
     * Executes INSERT or UPDATE operations on the {@code AudioDevice} table.
     * <p>
     * For new records the primary key is generated by the database using {@code RETURNING} and is
     * copied into the domain object. UPDATE statements bind every field to keep the
     * {@link RowMapper} consistent and to avoid partial updates.
     * </p>
     *
     * @param d audio device whose properties are inserted into the SQL statement via named
     *          parameters.
     * @return the persisted audio device with its {@code AudioDeviceID} set.
     */
    @Override
    public AudioDevice save(AudioDevice d) {
        boolean isNew = d.getAudioDeviceID() == null;
        if (isNew) {
            String sql = """
                INSERT INTO AudioDevice (ClientID, AudioDeviceBrand, DeviceSerialNr, AudioDeviceFirmware, DeviceType, Direction)
                VALUES (:client, :brand, :sn, :fw, :type, :direction)
                RETURNING AudioDeviceID
                """;
            UUID id = jdbc.queryForObject(sql, new MapSqlParameterSource()
                    .addValue("client", d.getClientID())
                    .addValue("brand", d.getAudioDeviceBrand())
                    .addValue("sn", d.getDeviceSerialNr())
                    .addValue("fw", d.getAudioDeviceFirmware())
                    .addValue("type", d.getDeviceType())
                    .addValue("direction", d.getDirection()), UUID.class);
            d.setAudioDeviceID(id);
        } else {
            String sql = """
                UPDATE AudioDevice SET
                    ClientID = :client, AudioDeviceBrand = :brand, DeviceSerialNr = :sn,
                    AudioDeviceFirmware = :fw, DeviceType = :type, Direction = :direction
                WHERE AudioDeviceID = :id
                """;
            jdbc.update(sql, new MapSqlParameterSource()
                    .addValue("id", d.getAudioDeviceID())
                    .addValue("client", d.getClientID())
                    .addValue("brand", d.getAudioDeviceBrand())
                    .addValue("sn", d.getDeviceSerialNr())
                    .addValue("fw", d.getAudioDeviceFirmware())
                    .addValue("type", d.getDeviceType())
                    .addValue("direction", d.getDirection()));
        }
        return d;
    }
}
